-- PostgreSQL schema for the Hermes Kanban board.
--
-- Mirrors schema_sqlite.sql with these mechanical dialect changes:
--   * INTEGER PRIMARY KEY AUTOINCREMENT   -> BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
--   * INTEGER (unix timestamps & counters) -> BIGINT (safer, no overflow concern)
--   * TEXT  -> TEXT (kept identical; JSON payloads are stored as TEXT to
--                    preserve perfect round-trip parity with SQLite for
--                    the initial migration. A later schema_version may
--                    convert ``payload`` and ``metadata`` to JSONB once
--                    the codebase stops treating them as opaque strings.)
--
-- Per-board PG schema isolation: this file is executed against a
-- search_path set to kanban_<board_slug>. So a multi-board install
-- has e.g. kanban_default.tasks, kanban_trading_lab.tasks, etc., and
-- a worker pinned to one board never sees another board's rows.
--
-- All additive columns and indexes from the SQLite migration pass
-- (_migrate_add_optional_columns) are in this initial schema, so
-- fresh PG schemas never need post-creation migration.

CREATE TABLE IF NOT EXISTS tasks (
    id                   TEXT PRIMARY KEY,
    title                TEXT NOT NULL,
    body                 TEXT,
    assignee             TEXT,
    status               TEXT NOT NULL,
    priority             BIGINT DEFAULT 0,
    created_by           TEXT,
    created_at           BIGINT NOT NULL,
    started_at           BIGINT,
    completed_at         BIGINT,
    workspace_kind       TEXT NOT NULL DEFAULT 'scratch',
    workspace_path       TEXT,
    branch_name          TEXT,
    claim_lock           TEXT,
    claim_expires        BIGINT,
    tenant               TEXT,
    result               TEXT,
    idempotency_key      TEXT,
    consecutive_failures BIGINT NOT NULL DEFAULT 0,
    worker_pid           BIGINT,
    last_failure_error   TEXT,
    max_runtime_seconds  BIGINT,
    last_heartbeat_at    BIGINT,
    current_run_id       BIGINT,
    workflow_template_id TEXT,
    current_step_key     TEXT,
    skills               TEXT,
    model_override       TEXT,
    max_retries          BIGINT,
    goal_mode            BIGINT NOT NULL DEFAULT 0,
    goal_max_turns       BIGINT,
    session_id           TEXT,
    project_id           TEXT,
    block_kind           TEXT,
    block_recurrences    BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS task_links (
    parent_id  TEXT NOT NULL,
    child_id   TEXT NOT NULL,
    PRIMARY KEY (parent_id, child_id)
);

CREATE TABLE IF NOT EXISTS task_comments (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id    TEXT NOT NULL,
    author     TEXT NOT NULL,
    body       TEXT NOT NULL,
    created_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS task_events (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id    TEXT NOT NULL,
    run_id     BIGINT,
    kind       TEXT NOT NULL,
    payload    TEXT,
    created_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS task_runs (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id             TEXT NOT NULL,
    profile             TEXT,
    step_key            TEXT,
    status              TEXT NOT NULL,
    claim_lock          TEXT,
    claim_expires       BIGINT,
    worker_pid          BIGINT,
    max_runtime_seconds BIGINT,
    last_heartbeat_at   BIGINT,
    started_at          BIGINT NOT NULL,
    ended_at            BIGINT,
    outcome             TEXT,
    summary             TEXT,
    metadata            TEXT,
    error               TEXT
);

CREATE TABLE IF NOT EXISTS task_attachments (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id      TEXT NOT NULL,
    filename     TEXT NOT NULL,
    stored_path  TEXT NOT NULL,
    content_type TEXT,
    size         BIGINT NOT NULL DEFAULT 0,
    uploaded_by  TEXT,
    created_at   BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS kanban_notify_subs (
    task_id          TEXT NOT NULL,
    platform         TEXT NOT NULL,
    chat_id          TEXT NOT NULL,
    thread_id        TEXT NOT NULL DEFAULT '',
    user_id          TEXT,
    notifier_profile TEXT,
    created_at       BIGINT NOT NULL,
    last_event_id    BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (task_id, platform, chat_id, thread_id)
);

CREATE TABLE IF NOT EXISTS kanban_schema_version (
    version    BIGINT PRIMARY KEY,
    applied_at BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_tasks_assignee_status ON tasks(assignee, status);
CREATE INDEX IF NOT EXISTS idx_tasks_status          ON tasks(status);
CREATE INDEX IF NOT EXISTS idx_links_child           ON task_links(child_id);
CREATE INDEX IF NOT EXISTS idx_links_parent          ON task_links(parent_id);
CREATE INDEX IF NOT EXISTS idx_comments_task         ON task_comments(task_id, created_at);
CREATE INDEX IF NOT EXISTS idx_events_task           ON task_events(task_id, created_at);
CREATE INDEX IF NOT EXISTS idx_runs_task             ON task_runs(task_id, started_at);
CREATE INDEX IF NOT EXISTS idx_runs_status           ON task_runs(status);
CREATE INDEX IF NOT EXISTS idx_attachments_task      ON task_attachments(task_id, created_at);
CREATE INDEX IF NOT EXISTS idx_notify_task           ON kanban_notify_subs(task_id);
CREATE INDEX IF NOT EXISTS idx_tasks_tenant          ON tasks(tenant);
CREATE INDEX IF NOT EXISTS idx_tasks_idempotency     ON tasks(idempotency_key);
CREATE INDEX IF NOT EXISTS idx_tasks_session_id      ON tasks(session_id);
CREATE INDEX IF NOT EXISTS idx_events_run            ON task_events(run_id, id);
